name: default
dependencies:
  - numpy
  - jupyter
  - scipy
  - matplotlib
  - scikit-learn
  - spacy
  - pip
  - nltk
  - pip:
    - https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.11.0-cp35-cp35m-linux_x86_64.whl
